### ISSUE TITLE
[Enhancement]: Notification pour note " N.Not "

### ISSUE THREAD

**Issue by matheodupuy** [PapillonApp/Papillon#104]
### Description du problème

Affichage de " Vous n'avez pas été noté(é) pour ce cours. "

### Description de l'amélioration

Changer "Vous n'avez pas été noté(é) pour ce cours." par "Vous n'avez pas été noté(é) pour ce contrôle." ou "Vous n'avez pas été noté(é) pour cette évaluation."

### Contexte supplémentaire

![IMG_2654](https://github.com/PapillonApp/Papillon/assets/114299376/a33a7e5f-7f96-44c6-8a20-d072daca57c3)

**Comment by Vilerio** [comment]
réglé ici, merci du report ! https://github.com/PapillonApp/Papillon/commit/06d602685bd509eb9b3502f6124887da8aee0a5d
