### ISSUE TITLE
[Enhancement]: Ne dépendre d'aucun serveur pour les disclaimers légaux

### ISSUE THREAD

**Issue by maelgangloff** [PapillonApp/Papillon#115]
### Description du problème

Le contenu de cet issue est repris de mon commentaire : https://github.com/PapillonApp/Papillon/pull/114#pullrequestreview-1961372947

> L'utilisation de https://locations.getpapillon.xyz ne fait que déplacer le problème posé par l'existence de l'API https://api.getpapillon.xyz.
> 
> Que faire si ce serveur venait à être piraté ? Que faire si ce serveur venait à tomber en panne ? Que faire si ce serveur est surchargé ?
> 
> **Nous nous devons d'être irréprochables en matière de sécurité et d'information envers les utilisateurs finaux**.
> 
> L'existence d'une telle API est une grave erreur. Il vaut mieux que l'application ne puisse contacter que les API des ENT pour que l'on ne puisse rien nous reprocher concernant le traitement des données (logs d'adresses IP, ...).
> 

### Description de l'amélioration

> Le mieux serait d'inclure les disclaimers directement dans le code source de l'app. S'il faut déployer rapidement de nouvelles mentions auprès des utilisateurs, il nous suffira de pousser les utilisateurs à mettre à jour leur app (via une annonce sur le serveur Discord, via les consoles des stores, etc.)

**Comment by azgaresncf** [comment]
> ### Description du problème
> 
> Le contenu de cet issue est repris de mon commentaire : [#114 (review)](https://github.com/PapillonApp/Papillon/pull/114#pullrequestreview-1961372947)
> 
> > L'utilisation de https://locations.getpapillon.xyz ne fait que déplacer le problème posé par l'existence de l'API https://api.getpapillon.xyz.
> > Que faire si ce serveur venait à être piraté ? Que faire si ce serveur venait à tomber en panne ? Que faire si ce serveur est surchargé ?
> > **Nous nous devons d'être irréprochables en matière de sécurité et d'information envers les utilisateurs finaux**.
> > L'existence d'une telle API est une grave erreur. Il vaut mieux que l'application ne puisse contacter que les API des ENT pour que l'on ne puisse rien nous reprocher concernant le traitement des données (logs d'adresses IP, ...).
> 
> ### Description de l'amélioration
> 
> > Le mieux serait d'inclure les disclaimers directement dans le code source de l'app. S'il faut déployer rapidement de nouvelles mentions auprès des utilisateurs, il nous suffira de pousser les utilisateurs à mettre à jour leur app (via une annonce sur le serveur Discord, via les consoles des stores, etc.)
> 
> ### Contexte supplémentaire
> 
> _No response_

C'est une bonne idée. Reste plus qu'à essayer de le mettre en place et de tester.

Dans tous les cas, les mises à jour, en règle générale, se font automatiquement.

**Comment by Vilerio** [comment]
Du coup la même PR règle en partie ce problème, même si je compte implémenter, quand elle sera acceptée, des messages par défaut

**Comment by Vilerio** [comment]
C'est fait, les disclaimers légaux sont maintenants hardcodés !
