### ISSUE TITLE
[Enhancement]: Modification des icônes proposées

### ISSUE THREAD

**Issue by Vilerio** [PapillonApp/Papillon#154]
### Description du problème

Timo (alokation) avait fait une nouvele version de son icône iOS 6

### Description de l'amélioration

![image](https://github.com/PapillonApp/Papillon/assets/69359417/7bb036cd-c146-4384-8c8e-79c43b37c0ac)

**Comment by Vilerio** [comment]
donc faut la modifier

**Comment by Sacha338** [comment]
je l'ai fait passé ici : https://github.com/PapillonApp/Papillon/pull/161
