### ISSUE TITLE
Pouvoir trier les catégories dans vie scolaire 

### ISSUE THREAD

**Issue by anaelchevillard** [PapillonApp/Papillon#186]
### Description du problème

Il peut arriver qu’on est beaucoup d’absence (comme moi) et sur Papillon les absences sont tout en haut, ensuite c’est les retards puis les heures de colle. Ce qui fait qu’on doit scroll pendant longtemps quand on veut une information et on se perd un peu dedans 

### Description de l'amélioration

Je pense qu’il serait intuitif de pouvoir choisir la catégorie qu’on veut voir, enfin de pouvoir trier. On le fait déjà dans les messages et les notes avec l’onglet en haut à droite. Je pense qu’il serait alors logique de pouvoir faire de même dans vie scolaire 

### Contexte supplémentaire

![IMG_5962](https://github.com/PapillonApp/Papillon/assets/143846034/75a7ccc6-0ec6-4373-84a1-bb8f6a87184c)
![IMG_5963](https://github.com/PapillonApp/Papillon/assets/143846034/562d6283-c78d-4083-bb56-9350dc2c012c)

**Comment by Vilerio** [comment]
> ### Description du problème
> Il peut arriver qu’on est beaucoup d’absence (comme moi) et sur Papillon les absences sont tout en haut, ensuite c’est les retards puis les heures de colle. Ce qui fait qu’on doit scroll pendant longtemps quand on veut une information et on se perd un peu dedans
> 
> ### Description de l'amélioration
> Je pense qu’il serait intuitif de pouvoir choisir la catégorie qu’on veut voir, enfin de pouvoir trier. On le fait déjà dans les messages et les notes avec l’onglet en haut à droite. Je pense qu’il serait alors logique de pouvoir faire de même dans vie scolaire
> 
> ### Contexte supplémentaire
> ![IMG_5962](https://private-user-images.githubusercontent.com/143846034/323523463-75a7ccc6-0ec6-4373-84a1-bb8f6a87184c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NTI1MTMsIm5iZiI6MTcxMzY1MjIxMywicGF0aCI6Ii8xNDM4NDYwMzQvMzIzNTIzNDYzLTc1YTdjY2M2LTBlYzYtNDM3My04NGExLWJiOGY2YTg3MTg0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQyMjMwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTUxNTg5ZTE0YWUzOWMyOWU4OGE2NWVjZTMyZTE4NDZmOTA3YzVhYjFkYmNiOWRjYjNkMzYwODQwNTE5MTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-YjrL0kc-ilkWv7C-wZ-Cjik-oV8iQCU7LPszjiMVOI) ![IMG_5963](https://private-user-images.githubusercontent.com/143846034/323523471-562d6283-c78d-4083-bb56-9350dc2c012c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NTI1MTMsIm5iZiI6MTcxMzY1MjIxMywicGF0aCI6Ii8xNDM4NDYwMzQvMzIzNTIzNDcxLTU2MmQ2MjgzLWM3OGQtNDA4My1iYjU2LTkzNTBkYzJjMDEyYy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjBUMjIzMDEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmQzNjgwNDM1YzkwNTEwMzAwZDY1ZDZjOWJkOTNhYWE5ZmEzMDZlMGQzZWUzYWM2ODVhMzgyNTkxMjMwMTVmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0j0-1Im3VXIr4IFo5eKz9eK1E_v5xnoBMP-8yfAqNmU)

En lien avec l'implémentation des observations, #190
