### ISSUE TITLE
[BUG] BlankScreen lorsque on tente de se localiser à l’étranger 

### ISSUE THREAD

**Issue by Sacha338** [PapillonApp/Papillon#189]
### Description du problème

Lorsque j’essaie de trouver des établissements autour de moi mais qu’il n’y en a pas, un écran vide s’affiche. 

### Description de l'amélioration

Ajouter une écran du style : « Aucun établissement se trouve à proximité de vous …. »

**Comment by tom-theret** [comment]
Effectivement, j'y travail !

**Comment by tom-theret** [comment]
fixé : 
- https://github.com/PapillonApp/Papillon/commit/66e07fdd152792b26cf0cbecfa1dd325288bb505
- https://github.com/PapillonApp/Papillon/commit/f00cd41ebf16999035c427aed42fe562597fe3e3
