### ISSUE TITLE
[Enhancement]: Ajouter les observations de Pronote

### ISSUE THREAD

**Issue by Vexcited** [PapillonApp/Papillon#190]
### Description du problème

Il manque des sections dans la page de vie scolaire.

### Description de l'amélioration

Ajouter la section des observations. Une observation est un défaut de carnet ou tout autre chose qui est attribué lors de l'appel en cours. Voir l'exemple ci-dessous.

![image](https://github.com/PapillonApp/Papillon/assets/59152884/cfb3ebbc-af42-42f6-8f9c-d3d57bf16500)

### Contexte supplémentaire

Supporté dans Pawnote depuis la version `0.20.0`.

**Comment by TinAD17tin** [comment]
Au ptn j’avais remarqué ça (pour ma première observation au collège), j’avais préparé les captures mais oublie de post, bien joué !

**Comment by Vilerio** [comment]
Je m'en occupe, je t'en avais parlé sur Discord il y a un moment !

**Comment by Vilerio** [comment]
ah tu t'es assigné, bah comme tu veux

**Comment by Vexcited** [comment]
> ah tu t'es assigné, bah je te la laisse

Je l'ai déjà implémenté même... mais dans mon fork pour l'instant.
Je vais ouvrir une PR en brouillon pour résumer tout ce que j'ai fais jusqu'à maintenant.

**Comment by Vilerio** [comment]
Ce sera fait au merge de #192
