### ISSUE TITLE
[Enhancement]: iOS : Pouvoir choisir sa couleur d’accentuation comme la V5

### ISSUE THREAD

**Issue by Orafilynie** [PapillonApp/Papillon#191]
### Description du problème

Pas de problème, juste une proposition de feature

### Description de l'amélioration

Pouvoir choisir la couleur d’accentuation (couleur de l’app si je peut l’appeler comme ca) de l’application comme sur la v5

**Comment by Louis-htmlcss** [comment]
@Orafilynie tu parles de la couleur avec material you car sinon ta juste a modifié la couleur d'accentuation de ton téléphone

**Comment by Orafilynie** [comment]
Oups j’ai complètement oublié de preciser iOS

**Comment by Louis-htmlcss** [comment]
@Louis-htmlcss ah ok je comprend mieux maintenant

**Comment by anaelchevillard** [comment]
Hello ! Ceci est désormais impossible à faire car nous utilisons les couleurs des cours ! Ce qui fait qu'il n'est pas possible d'intégrer la modification de couleur comme à la v5. Celle-ci modifiait le header et quelques autres éléments mais maintenant c'est les couleurs des cours qui gère tout ça.

**Comment by Sacha338** [comment]
Du coup on peut fermer ?
