### ISSUE TITLE
« Pause méridienne » s’adapte aux cours annulés 

### ISSUE THREAD

**Issue by anaelchevillard** [PapillonApp/Papillon#199]
### Description du problème

Quand un cours est annulé et touche la pause méridienne, la pause méridienne ne s’adapte pas

### Description de l'amélioration

Il faudrait qu’elle s’adapte aux cours annulés
![IMG_6128](https://github.com/PapillonApp/Papillon/assets/143846034/0c871044-4c0e-43ae-8ede-a042eeb9c1d6)

**Comment by Vilerio** [comment]
Je ne sais pas si c'est ce qu'à voulu dire Vince en l'implémentant, mais je considère plutôt pause méridienne comme le temps dédié de base pour manger, peu importe les modifications d'EDT

**Comment by LeGeek01** [comment]
je suis de l'avis de Vilerio, je ne pense pas qu'il serait nécessaire de forcément adapter la pause, ça pourrait porter à confusion l'utilisateur final en voyant qu'un cours a dispawn sans savoir pourquoi
