### ISSUE TITLE
[Enhancement]: Créer une option dans les paramètres pour les actualités

### ISSUE THREAD

**Issue by Gabriel29306** [PapillonApp/Papillon#204]
### Description du problème

Actuellement sur la version `v6.6.3 beta`, lorsque je vais sur une actualité, elle est marquée par défaut comme lue.

### Description de l'amélioration

Je propose de permettre à l'utilisateur d'avoir une checkbox dans les paramètre (ou ailleurs) pour choisir si les actualités doivent être marqués comme lu directement ou si il y a besoin d'une action manuelle.

**Comment by LeGeek01** [comment]
il me semble qu'il est possible de marquer une actualité comme non-lu (sur iOS uniquement cependant si ma mémoire est bonne), le but serait donc de déployer cette fonctionnalité sur android

**Comment by LeGeek01** [comment]
après check c'est effectivement uniquement dispo sur iOS

**Comment by Gabriel29306** [comment]
Pourquoi, ce n'est pas en react directement ?
