### ISSUE TITLE
L'onglet Vie Scolaire fait crash l'app

### ISSUE THREAD

**Issue by Astrow25** [PapillonApp/Papillon#21]
https://github.com/PapillonApp/Papillon/assets/76118368/975c93dd-2260-4e66-9a13-e04339f56ce4

**Comment by NonozgYtb** [comment]
Il me semble que ce n'est plus le cas, à tester avec la dernière version (dernier commit, pas dernière beta)

**Comment by LeGeek01** [comment]
Effectivement ce bug sur la version dev n'est plus d'actualité, cette issue peut donc être fermée
