### ISSUE TITLE
Bloquage login

### ISSUE THREAD

**Issue by Astrow25** [PapillonApp/Papillon#23]
"Connexion en cours" reste affiché indéfiniment.

![Screenshot_20220925-181107_Chrome.png](https://user-images.githubusercontent.com/76118368/192153675-0188cb03-6c36-490d-916f-1d2f12c732b7.png)

**Comment by lucas-luchack** [comment]
Les identifiants entrés sont-ils corrects ?
Votre authentification passe-t-elle par un ENT, si oui, l'avez-vous bien sélectionné ?

**Comment by Astrow25** [comment]
oui ça fonctionne actuellement avec l'app (3.6 android) mais pas sur le site

**Comment by ecnivtwelve** [comment]
> oui ça fonctionne actuellement avec l'app (3.6 android) mais pas sur le site

T'as pas eu de message d'erreur ?

**Comment by Astrow25** [comment]
nop

**Comment by shimataa** [comment]
Même issue la connexion charge pour toujours aucun message d'erreur et impossible de se connecter.
