### ISSUE TITLE
[Enhancement]: Publicité (non lucratif)

### ISSUE THREAD

**Issue by Slysoks** [PapillonApp/Papillon#279]
### Description du problème

J'ai une idée pour avoir un meilleur financement de l'application afin de payer les charges (ex: publication Play Store & App Store).

### Description de l'amélioration

Il suffirait d'ajouter un bouton dans la catégorie <b>Soutenir Papillon</b> qui permet de regarder une publicité afin d'aider le projet. On pourrait donc ajouter un bouton <b>Regarder une publicité</b> permettant de regarder une publicité et donc apporter un soutien. Je propose également un système pour ajouter un grade / classement en fonction du nombre de pub regardées (ex: <i>Petit Donateur;Donateur;Donateur Avancé;Donateur Expérimenté</i>). Après il me semble que ce projet est à but non lucratif, donc aucun avantages ne sera donné en fonction du nombre de pubs regardées.

**Comment by LeGeek01** [comment]
Salut,
Papillon est effectivement à but non lucratif, et rajouter des publicités dans l'appli est impensable.
Que serait l'action de ce bouton ? Rediriger sur un site permettant de regarder des publicités ?

**Comment by Slysoks** [comment]
Le but est de cliquer sur le bouton pour regarder une publicité (par exemple via [Unity Ads](https://unity.com/fr/products/unity-ads)) pour soutenir le projet. Ce serait donc une publicité <b>intentionnelle</b> de la part de l'utilisateur et aucun avantage n'en sera délivré (mis a part par exemple un titre motivant à en regarder). Mais cela n'est nécéssaire uniquement si Papillon ne génère pas assez d'argent pour gérer les charges (par exemple les 100$ par ans pour publier dans l'App Store).

**Comment by godetremy** [comment]
Hello, 👋

Pour moi, cela semble être une mauvaise idée. Dans l'idée, c'est pas bête, mais inclure des publicités sur Papillon ajouterait également des modules à celui ci qui pourrait rapidement venir à augmenter la taille de Papillon, ainsi que niveau sécurité également. 

Certaines plateformes de dons proposent ta fonction directement depuis la plateforme, ils serait peut-être plus interessant de voir à cela. Même si, le prix que nous obtiendrons de celle ci sera relativement minime. Les pubs sur le web rapporte de moins en moins..!

**Comment by Slysoks** [comment]
Et j'ai aussi un peu peur de ça : ![Screenshot_20240817_093639_Google Play Store.png](https://github.com/user-attachments/assets/26ff19f7-02a0-4561-abc7-0c9ba85c1da9)

**Comment by tom-theret** [comment]
Hello, outre la publicité sa créer du pistage ce qui est contraire aux valeurs de Papillon.

**Comment by Slysoks** [comment]
Je pense donc pouvoir fermer ce ticket en partant sur un avis unanime de votre part.
