### ISSUE TITLE
Ne pas afficher le jour quand aucun cours

### ISSUE THREAD

**Issue by Christian-Martins** [PapillonApp/Papillon#35]
Bonjour,

Il serait bien, comme sur Pronote, de n'afficher que les jours avec des cours de prévu.

Bien à vous.

**Comment by ecnivtwelve** [comment]
Cela rendrait l'UX étrange par rapport aux jours qui sautent vu que c'est un calendrier et pas un agenda comme sur Pronote

**Comment by create-juicey-app** [comment]
Vrai, sa respecte pas l'une des règle material design de skip les jours comme sa.
