### ISSUE TITLE
Duplicata des cours quand remplacement

### ISSUE THREAD

**Issue by Labfox** [PapillonApp/Papillon#36]
Les cours se dupliquent quand il y a un remplacement
(Photo en cours d'upload)

**Comment by Labfox** [comment]
https://quickshare.samsungcloud.com/mwBidgROuNwN

**Comment by LeGeek01** [comment]
> Je réouvre l'issue car elle n'est pas réparée _(je fais ça au plus vite)_

@ecnivtwelve c'est pas un problème, ça peut être une suggestion pour une future option, mais ce qu'il met dans son rec c'est le fonctionnement normal de pronote

**Comment by ecnivtwelve** [comment]
Oui mais pas l'usage attendu d'un user

**Comment by ecnivtwelve** [comment]
Fixé ici btw https://github.com/PapillonApp/Papillon/commit/904536d98266b037bffc74236b888fd55170f8e3
