### ISSUE TITLE
Nombre de cours restants beugés

### ISSUE THREAD

**Issue by Labfox** [PapillonApp/Papillon#38]
![Screenshot_20230907_192609_Papillon.jpg](https://github.com/PapillonApp/Papillon/assets/108928065/31b65dcf-f234-4228-ac70-2dc4b8cf70a9)

**Comment by ecnivtwelve** [comment]
Fixé ici https://github.com/PapillonApp/Papillon/commit/55a44e03e25994cfe0d6d229f708fff010f7000c
