### ISSUE TITLE
[Enhancement]: Ajout corrigé et sujet dans les notes

### ISSUE THREAD

**Issue by Vexcited** [PapillonApp/Papillon#38]
### Description du problème

Voir le post sur le serveur Discord : <https://discord.com/channels/1014931881906675712/1210236400746893393>

---

Pas de corrigé ni de sujet affiché dans la page de visualisation de note.

### Description de l'amélioration

Comme le titre l'indique.

### Contexte supplémentaire

Pawnote supporte déjà cette fonctionnalité, il faut juste l'ajouter dans les types et l'interface.

**Comment by LeGeek01** [comment]
@Vexcited du nouveau ?

**Comment by Vexcited** [comment]
J'ai pas encore commencé, va falloir que je fasse une branche pour ça car j'avoue que je sais pas trop où ça va aller dans l'UI des notes.
