### ISSUE TITLE
[Enhancement]: Signature et chiffrement GPG des messages Papillon

### ISSUE THREAD

**Issue by Vilerio** [PapillonApp/Papillon#49]
### Description du problème

Faire en sorte qu'on puisse, entre deux utilisateurs, signer et chiffrer des messages envoyés, grâce à des clés GPG

### Description de l'amélioration

Faire en sorte qu'on puisse, entre deux utilisateurs, signer et chiffrer des messages envoyés, grâce à des clés GPG

**Comment by Vilerio** [comment]
utiliser : https://www.openkeychain.org/

**Comment by ecnivtwelve** [comment]
impossible -> tu ne peux pas tenir de discussions entre deux utilisateurs de Papillon puisque seuls les élèves ont accès à l'app, les messages seraient donc tous indéchiffrables

**Comment by Vilerio** [comment]
> impossible -> tu ne peux pas tenir de discussions entre deux utilisateurs de Papillon puisque seuls les élèves ont accès à l'app, les messages seraient donc tous indéchiffrables

Pourquoi deux élèves ne pourraient pas échanger entre eux ?

**Comment by Vilerio** [comment]
Et si l'établissement désactive l'option entre les élèves, on pourra implémenter le chiffrement gpg quand Papillon sera accessible à tous !
