### ISSUE TITLE
[BETA] La barre de texte non-alignée correctment

### ISSUE THREAD

**Issue by azgaresncf** [PapillonApp/Papillon#5]
La barre en dessous du texte n'est pas correctement alignée sur le choix de l'URL Pronote.

![Screenshot_20230831_215454_Papillon](https://github.com/PapillonApp/Papillon/assets/50982832/07288cdb-3e7b-4828-9e6d-d7df5ac39be0)

**Comment by MRakox** [comment]
Le soucis vient probablement de [ce package](https://github.com/shimohq/react-native-prompt-android#readme) qui n'est plus maintenu...

**Comment by azgaresncf** [comment]
> Le soucis vient probablement de [ce package](https://github.com/shimohq/react-native-prompt-android#readme) qui n'est plus maintenu...

Ah... Merci de l'avoir prévenu en tout cas.

**Comment by MRakox** [comment]
La dernière MAJ date d'il y a 4 ans ça peut être une bonne idée de changer de lib pour régler le problème (et d'autres éventuels)

**Comment by azgaresncf** [comment]
> La dernière MAJ date d'il y a 4 ans ça peut être une bonne idée de changer de lib pour régler le problème (et d'autres éventuels)

Il est vrai qu'il en faudrait trouver une mis à jour (vu que le développeur ne regarde visiblement pas les issues et les PR qu'il l'attende).

> Je conseillerai : https://github.com/mmazzarolo/react-native-dialog 
Ça m'a l'air d'être une bonne idée.

**Comment by ecnivtwelve** [comment]
Ouais pourquoi pas ! Je réouvre l'issue tant que c'est pas implémenté

**Comment by ecnivtwelve** [comment]
Fixé ici : https://github.com/PapillonApp/Papillon/commit/fc1dfb4d05766ff6191d0d95bda58ef6d7c674a9
