### ISSUE TITLE
Problème de redondance pour les paramètres de notifications

### ISSUE THREAD

**Issue by lvllaby** [PapillonApp/Papillon#50]
### Description du problème

Les paramètres pour les notifications sont présents dans deux endroits de l'application. Un onglet directement accessible depuis les paramètres et un autre accessible depuis "Apparence et fonctionnalité" dans les paramètres ce qui pose un problème de redondance. 

### Description de l'amélioration

Retirer les paramètres de notification de l'onglet apparence et fonctionnalité

**Comment by lvllaby** [comment]
https://github.com/PapillonApp/Papillon/assets/94006475/0c8d417e-05ac-418d-9862-58ae5dbc0edc

**Comment by Vilerio** [comment]
Ah d'accord sous Androïd, j'avais regardé que sous IOS

effectivement, c'est à corriger, même si ça ne pose pas de problème technique car c'est le même menu

Merci du report !

**Comment by Sacha338** [comment]
Vous comptez plutôt le supprimer l'onglet qui apparaît directement ou l'onglet qui apparaît dans Apparence et Fonctionnalité ?

**Comment by ecnivtwelve** [comment]
Fixé ici --> https://github.com/PapillonApp/Papillon/commit/0635cf01be5fd24759025dee550eb410613e9b77
