### ISSUE TITLE
Jour dans l’emploi du temps

### ISSUE THREAD

**Issue by TheTiger72** [PapillonApp/Papillon#50]
### Description du problème

Ont ne voit pas les jours

### Description de l'amélioration

Il serait bien d’ajouter le jour au dessous dans l’emploi temps car seul la date s’affiche et on ne sais pas à quel jour on est.
Donc en plus d’avoir le 04/09/2023 de mettre à côté Lundi… etc

**Comment by Spectralo** [comment]
Sur la dernière version le jour est bien présent a côté de la date

**Comment by TheTiger72** [comment]
Toujours pas de mon côté sur la version 6.2.3 Testflight iPhone 13 iOS 17.1 beta 3

**Comment by LeGeek01** [comment]
@TheTiger72 c'est encore le cas avec la dernière version ?

**Comment by TheTiger72** [comment]
> @TheTiger72 c'est encore le cas avec la dernière version ?

J'ai que la 6.3.2 de disponible dans TestFlight. Et oui j'ai toujours pas les jours sur cette version.

**Comment by LeGeek01** [comment]
tu peux envoyer un screen ?

**Comment by TheTiger72** [comment]
> tu peux envoyer un screen ?

![image](https://github.com/PapillonApp/Papillon/assets/84013544/ee7f668c-d0e9-4798-893b-2ce7b0785823)

**Comment by TheTiger72** [comment]
C'est bon
La dernière version est sortie sur TestFlight et les jours sont là !
