### ISSUE TITLE
[Enhancement]: Enlevé le mot "Salle"

### ISSUE THREAD

**Issue by shidos-anael** [PapillonApp/Papillon#55]
### Description du problème

Quand notre salle contient déjà le mot salle, ça fai Salle **salles de labo**
![image](https://github.com/PapillonApp/Papillon/assets/143846034/a4541d9b-b1cc-4271-94a2-030c86e94946)

### Description de l'amélioration

Enlevé le mot "Salle" si le nom de la salle contient déjà le mon Salle
Si l'app détecte que le nom de la salle contient déjà le mot salle, alors enlevé le mot salle de papillon

**Comment by okayhappex** [comment]
Honnêtement, je pense pas que le fait de s'occuper des cas particuliers soit gérable par les développeurs. Je dis que c'est un cas particulier car la plupart des établissement ne mettent pas le mot "salle" devant

**Comment by Vilerio** [comment]
La plupart des établissements n'ont effectivement pas le mot "salle" devant, mais j'avais fait un mini-patch pour ça, faut que je le test avec plusieurs noms de salle puis que je le push

**Comment by okayhappex** [comment]
Ça marche

**Comment by Vilerio** [comment]
fixed https://github.com/PapillonApp/Papillon/commit/34584d41e9ebced6ad1712024dc1ab2180a8fcb3
