### ISSUE TITLE
[Enhancement]: Ajouter au calendrier

### ISSUE THREAD

**Issue by azerty1h00** [PapillonApp/Papillon#59]
### Description du problème

L’option pour mettre nos cours dans calendrier n’est plus disponible dans la nouvelle version 

### Description de l'amélioration

Bonjour, sur l’ancienne version, on pouvait mettre nos cours dans l’app calendrier sur iPhone mais avec la nouvelle mise à jour de papillon je n’arrive plus à le faire, ce serait bien de remettre l’option. Merci d’avance

**Comment by ecnivtwelve** [comment]
C'est déja pré-implémenté, ça arrive au plus vite

**Comment by azerty1h00** [comment]
D’accord merci

**Comment by ecnivtwelve** [comment]
Expo a mis à jour expo-calendar, ça arrive dans la semaine
https://expo.dev/changelog/2023/09-28-new-xcode-ios
