### ISSUE TITLE
[Enhancement]: Afficher clairement les « déposer ma copie »

### ISSUE THREAD

**Issue by TinAD17tin** [PapillonApp/Papillon#81]
### Description du problème

Les devoirs en mode « déposer ma copie » ne sont pas visible sans cliquer dessus.

### Description de l'amélioration

Une icône, une couleur, un texte, un logo, qui permettrait d’identifier les « déposer ma copie »

**Comment by Vilerio** [comment]
Ce sera réglé au merge de cette PR : https://github.com/PapillonApp/Papillon/pull/108
