### ISSUE TITLE
[Enhancement]: Ajout assistant de cours

### ISSUE THREAD

**Issue by TinAD17tin** [PapillonApp/Papillon#89]
### Description du problème

En anglais, tous les lundis on a une assistante venu des USA qui fait court avec la profs, ça nous permet d’apprendre un peu la culture de USA. Sur PRONOTE, elle est indiqué, mais pas sur Papillon, pourriez-vous ajouter cette fonction ?

### Description de l'amélioration

Ajouter les éventuels assistants de profs.

### Contexte supplémentaire

![IMG_5980](https://github.com/PapillonApp/Papillon/assets/163759571/7fe83bab-9865-4727-8e97-096a4a448e91)

**Comment by tom-theret** [comment]
@Vexcited je crois que Pawnote a besoin d'une modification

**Comment by Vexcited** [comment]
Intéressant, je vais voir ce qui manque dans ma fonction actuelle pour la rajouter.

**Comment by Vexcited** [comment]
Implementé dans Pawnote (https://github.com/LiterateInk/Pawnote/pull/24), sera release dans la version `0.20.0`.

**Comment by TinAD17tin** [comment]
Parfait merci et bien joué !
________________________________
De : Mikkel RINGAUD ***@***.***>
Envoyé : Tuesday, April 16, 2024 6:52:39 PM
À : PapillonApp/Papillon ***@***.***>
Cc : TinAD17tin ***@***.***>; Author ***@***.***>
Objet : Re: [PapillonApp/Papillon] [Enhancement]: Ajout assistant de cours (Issue #89)


Implementé dans Pawnote (LiterateInk/Pawnote#24<https://github.com/LiterateInk/Pawnote/pull/24>), sera release dans la version 0.20.0.

**Comment by Vilerio** [comment]
Ce sera fait au merge de #192
