### ISSUE TITLE
[Enhancement]: Mode horizontal / Mode iPad

### ISSUE THREAD

**Issue by TinAD17tin** [PapillonApp/Papillon#90]
### Description du problème

Tout est dans le titre, ajouter un mode horizontal, pour pouvoir mieux consulter Papillon sur des tablettes, ou même pouvoir le consulter sur son téléphone dans sa trousse 😉. Mais aussi en charge sur une borne couché, ou autre raison qui nous pousseraient au mode horizontal.

### Description de l'amélioration

Ajouter un mode horizontal

**Comment by Vilerio** [comment]
C'est en cours de design ;)

**Comment by TinAD17tin** [comment]
Parfait merci !
________________________________
De : Vilerio ***@***.***>
Envoyé : Sunday, March 24, 2024 2:06:18 PM
À : PapillonApp/Papillon ***@***.***>
Cc : TinAD17tin ***@***.***>; Author ***@***.***>
Objet : Re: [PapillonApp/Papillon] [Enhancement]: Mode horizontal (Issue #90)


C'est en cours de design ;)
