### ISSUE TITLE
[Enhancement]: Ajouter dispensé sur les cours sur lequel on est dispensé 

### ISSUE THREAD

**Issue by lvllaby** [PapillonApp/Papillon#98]
### Description du problème

Il n'y a pas marqué dispensé sur les cours sur lesquels on l'est

### Description de l'amélioration

Ajouter une indication que l'on est dispensé

**Comment by Vilerio** [comment]
@Vexcited Pawnote le permet ?

**Comment by Vilerio** [comment]
nice

**Comment by tom-theret** [comment]
fait : https://github.com/PapillonApp/Papillon/commit/f1c5ce7de3c2c768cb80cb7b7cbee248f746d019
